### ISSUE TITLE
Number of digits not respected

### ISSUE THREAD

**Issue by tanker11** [t1gr0u/rain-gauge-card#15]
The number of digits I can set for a sensor under HA settings is not respected and it shows the original one.

**Comment by t1gr0u** [comment]
@tanker11 thank you for using the plugin.
Are you talking about the precision?
If you are please have a look at https://github.com/t1gr0u/uv-index-card/issues/13#issuecomment-1542804310

**Comment by tanker11** [comment]
Thank you for the answer. Indeed, it is the same problem. I have set the precision of the entity, but the card shows the original precision with 14 digits...
Now I checked another custom card, and it is the same. Maybe HA does not hand over it correctly (?)
A workaround on another (custom-button) card is a js template:
label: |
  [[[
    return Math.round(entity.state*10)/10+"°C";
  ]]]

Would a similar solution be possible on your card?

**Comment by t1gr0u** [comment]
At the moment HA or HACS doesn't send this value, maybe in a future release?

Ideally I would prefer to not modify the value as this may generate more issues as everyone would like to see their value in a different way.

Maybe a future feature to be able to set the precision on the card.
```yaml
type: custom:rain-gauge-card
entity: sensor.rain_24h
show_warning: false
show_error: false
is_imperial: false
max_level: 3
precision: 10 
```
