### ISSUE TITLE
Proportional resizing of image in card

### ISSUE THREAD

**Issue by Saentist** [t1gr0u/rain-gauge-card#7]
Currently if size of card is 1x1 not standard 1x2 text is over image.
![image](https://user-images.githubusercontent.com/16975883/236419596-7dd61596-5797-4e0c-8c91-eed6a8424318.png)

``` yaml
type: horizontal-stack
cards:
  - type: custom:rain-gauge-card
    entity: sensor.daily_rain_rate_2
    hourly_rate_entity: sensor.hourly_rain_rate_2
  - type: custom:uv-index-card
    entity: sensor.uv_index
```

Gap bellow UV index is also strange.
